spring:
  application:
    name: oprpg-api
  datasource:
    url: jdbc:mysql://localhost:3306/one_piece_rpg
    username: oprpg
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: "votre_clé_secrète_pour_signer_les_tokens_jwt"
  expiration: 86400000 # 1 jour en millisecondes

server:
  port: 8080
